name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Cache Nix
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-ci-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-ci-${{ runner.os }}-${{ runner.arch }}-

      - name: Run checks
        shell: nix develop --command bash {0}
        run: pnpm install && pnpm e2e-ci
